language: python

python:
  - "2.7"

install: "pip install -r requirements.txt"

env:
    - NEO4J_VERSION="2.3.1"

jdk:
    - oraclejdk7  # needed for local Neo4j 2.0+

before_install:
    # install Neo4j locally:
    - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
    - neo4j-community-$NEO4J_VERSION/bin/neo4j start

script:
  - python test/test_all.py

branches:
  only:
    - master